import { Request, Response } from 'express';
import { geminiService } from '../services/ai-services/geminiService.js';
import { medicalReportService } from '../services/medicalReportService.js';
import fs from 'fs';
import path from 'path';
import winston from 'winston';

const logger = winston.createLogger({
  level: 'info',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.json()
  ),
  transports: [new winston.transports.Console()]
});

export async function handleAnalyzeReport(req: Request, res: Response) {
  const file = req.file;

  logger.info({ tag: '[UPLOAD]', message: 'Received upload request', hasFile: !!file, bodyKeys: Object.keys(req.body) });

  if (!file) {
    logger.warn({ tag: '[UPLOAD]', message: 'No file received in request — aborting' });
    return res.status(400).json({
      success: false,
      message: 'No report file uploaded. Please upload a PDF or image of your medical report.'
    });
  }

  logger.info({ tag: '[UPLOAD]', message: 'File received', filename: file.filename, originalname: file.originalname, mimetype: file.mimetype, size: file.size });

  const filePath = file.path;

  try {
    const systemPrompt = `You are a Senior Medical Diagnostics AI Specialist and Clinical Pathologist.
Analyze the uploaded medical report file (CBC, LFT, KFT, Lipid Profile, Thyroid, ECG, MRI, CT, etc.) and extract diagnostic parameters.
Focus on identifying abnormal readings, referencing standard ranges, predicting clinical significance, and recommending medical actions.

You must return a valid, well-formed JSON object ONLY. Do not wrap it in markdown code blocks or add prefix/suffix text.
JSON structure must match:
{
  "reportType": "string (e.g. CBC, Liver Function Test, Lipid Profile)",
  "patientName": "string | unknown",
  "reportDate": "string | unknown",
  "abnormalValues": [
    {
      "parameter": "string (e.g. Hemoglobin, SGPT, Cholesterol)",
      "value": "string",
      "referenceRange": "string",
      "severity": "Low | Medium | High",
      "explanation": "string"
    }
  ],
  "diseaseIndicators": ["string"],
  "recommendedSpecialist": "string (e.g. Cardiologist, Hematologist, Gastroenterologist)",
  "suggestedNextSteps": ["string"],
  "medicineInteractions": ["string (potential drug/therapy contradictions linked to these results)"],
  "trendAnalysis": "string (explain potential metabolic or health trend)",
  "healthAdvice": "string",
  "confidenceScore": number,
  "medicalDisclaimer": "This summary is generated by AI based on the uploaded clinical report and is for informational purposes only. Please consult a qualified medical professional for diagnosis."
}`;

    const userPrompt = `Please analyze the uploaded medical report. Extract all key parameters, flag abnormal results, and suggest clinical next steps in the defined JSON schema.`;
    const mimeType = file.mimetype;

    logger.info({ tag: '[OCR]', message: 'Reading file buffer for Gemini analysis', filePath, mimeType });
    const fileBuffer = fs.readFileSync(filePath);
    logger.info({ tag: '[OCR]', message: 'File buffer read successfully', bufferSize: fileBuffer.length });

    logger.info({ tag: '[GEMINI]', message: 'Calling geminiService.generateFromMedia', mimeType, bufferSize: fileBuffer.length });

    let aiResponse: string;
    try {
      aiResponse = await geminiService.generateFromMedia(
        userPrompt,
        mimeType,
        fileBuffer,
        systemPrompt,
        40000
      );
      logger.info({ tag: '[GEMINI]', message: 'Gemini response received', responseLength: aiResponse.length, preview: aiResponse.substring(0, 200) });
    } catch (geminiError: any) {
      logger.error({ tag: '[GEMINI]', message: 'Gemini analysis FAILED — cannot proceed', error: geminiError.message });
      if (fs.existsSync(filePath)) { try { fs.unlinkSync(filePath); } catch (e) {} }
      return res.status(500).json({
        success: false,
        message: `Gemini AI analysis failed: ${geminiError.message}`
      });
    }

    // Parse JSON from Gemini response
    let parsedResult: any = null;
    let parseError: string | null = null;
    try {
      let cleanJsonStr = aiResponse.trim();
      if (cleanJsonStr.startsWith('```')) {
        cleanJsonStr = cleanJsonStr.replace(/^```(json)?/, '').replace(/```$/, '').trim();
      }
      // Handle case where Gemini wraps response in additional text
      const jsonMatch = cleanJsonStr.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        cleanJsonStr = jsonMatch[0];
      }
      parsedResult = JSON.parse(cleanJsonStr);
      logger.info({ tag: '[GEMINI]', message: 'Gemini JSON parsed successfully', reportType: parsedResult.reportType, abnormalCount: parsedResult.abnormalValues?.length });
    } catch (parseErr: any) {
      parseError = parseErr.message;
      logger.warn({ tag: '[GEMINI]', message: 'Gemini JSON parse failed — using fallback structure', error: parseErr.message, rawResponse: aiResponse.substring(0, 300) });
      // Build a minimal valid result so the report still gets saved
      parsedResult = {
        reportType: 'Medical Report',
        patientName: 'Unknown',
        reportDate: new Date().toISOString().split('T')[0],
        abnormalValues: [],
        diseaseIndicators: [],
        recommendedSpecialist: 'General Physician',
        suggestedNextSteps: ['Consult a doctor for detailed analysis'],
        medicineInteractions: [],
        trendAnalysis: aiResponse.substring(0, 500),
        healthAdvice: 'Please consult your doctor.',
        confidenceScore: 70,
        medicalDisclaimer: 'AI-generated summary. Consult a qualified medical professional.'
      };
    }

    // Cleanup local uploaded file BEFORE saving to DB (file already in buffer)
    if (fs.existsSync(filePath)) {
      try { fs.unlinkSync(filePath); } catch (e) {}
    }

    // Save report to database
    const userId = (req.body && req.body.userId) ? req.body.userId : 'usr-901';
    logger.info({ tag: '[SAVE_REPORT]', message: 'Calling medicalReportService.saveReport', userId, reportType: parsedResult.reportType });

    let savedReport: any;
    try {
      savedReport = await medicalReportService.saveReport({
        userId,
        reportName: parsedResult.reportType || 'Clinical diagnostics report',
        reportType: parsedResult.reportType || 'Blood report',
        hospitalName: parsedResult.hospitalName || 'National Diagnostic Center',
        doctorName: parsedResult.doctorName || 'General Practitioner',
        reportDate: parsedResult.reportDate || new Date().toISOString().split('T')[0],
        fileName: file.originalname,
        fileUrl: '/uploads/' + file.filename,
        fileType: file.mimetype,
        ocrText: aiResponse,
        structuredJson: JSON.stringify(parsedResult),
        geminiAnalysis: parsedResult.trendAnalysis || '',
        abnormalValues: JSON.stringify(parsedResult.abnormalValues || []),
        healthScore: parsedResult.confidenceScore || 95,
        riskLevel: (parsedResult.abnormalValues?.length > 2) ? 'High' : 'Low',
        specialistRecommended: parsedResult.recommendedSpecialist || 'Physician',
        confidenceScore: parsedResult.confidenceScore || 95,
        status: 'COMPLETE'
      });

      logger.info({ tag: '[INSERT_SUCCESS]', message: 'Report saved to PostgreSQL successfully', reportId: savedReport.id, userId });
      
      // Auto-regenerate digital twin in background
      try {
        const { getOrCreateProfile, generateDigitalTwinLogic } = await import('./twinController.js');
        const profile = await getOrCreateProfile(userId);
        generateDigitalTwinLogic(userId, profile).catch(err => {
          logger.error({ tag: '[DATABASE]', message: 'Background Digital Twin generation failed after report upload', error: err.message });
        });
      } catch (twinErr: any) {
        logger.error({ tag: '[DATABASE]', message: 'Failed to trigger background twin generation', error: twinErr.message });
      }
    } catch (saveError: any) {
      logger.error({ tag: '[INSERT_FAILED]', message: 'medicalReportService.saveReport FAILED', error: saveError.message, stack: saveError.stack });
      // Still return the analysis result even if save fails
      return res.status(200).json({
        success: true,
        data: parsedResult,
        reportId: null,
        warning: 'Analysis completed but report could not be saved to database: ' + saveError.message,
        parseError,
        info: {
          filename: file.originalname,
          mimeType: file.mimetype,
          processedAt: new Date().toISOString()
        }
      });
    }

    logger.info({ tag: '[RESPONSE]', message: 'Sending success response', reportId: savedReport.id });

    return res.status(200).json({
      success: true,
      data: parsedResult,
      reportId: savedReport.id,
      parseError,
      info: {
        filename: file.originalname,
        mimeType: file.mimetype,
        processedAt: new Date().toISOString()
      }
    });

  } catch (error: any) {
    if (fs.existsSync(filePath)) {
      try { fs.unlinkSync(filePath); } catch (e) {}
    }
    logger.error({ tag: '[UPLOAD]', message: 'Unhandled error in handleAnalyzeReport', error: error.message, stack: error.stack });
    return res.status(500).json({
      success: false,
      message: error.message || 'An error occurred during medical report analysis.'
    });
  }
}
