import { Router } from 'express';
import aiRoutes from './ai.routes.js';
import analyticsRoutes from './analytics.routes.js';
import authRoutes from './auth.routes.js';
import campaignRoutes from './campaign.routes.js';
import reportRoutes from './report.routes.js';
import assistantRoutes from './assistant.routes.js';
import medicineRoutes from './medicine.routes.js';
import systemRoutes from './system.routes.js';
import twinRoutes from './twin.routes.js';
import surveillanceRoutes from './surveillance.routes.js';
import adminRoutes from './admin.routes.js';
import healthExchangeRoutes from './healthExchange.routes.js';
import hospitalRoutes from './hospital.routes.js';
import doctorRoutes from './doctor.routes.js';
import appointmentRoutes from './appointment.routes.js';
import laboratoryRoutes from './laboratory.routes.js';
import pharmacyRoutes from './pharmacy.routes.js';
import voiceAssistantRoutes from './voiceAssistant.routes.js';
import motherChildRoutes from './motherChild.routes.js';
import governmentSchemesRoutes from './governmentSchemes.routes.js';
import emergencyRoutes from './emergency.routes.js';
import symptomAssessmentRoutes from './symptomAssessment.routes.js';
import familyRoutes from './family.routes.js';
import telemedicineRoutes from './telemedicine.routes.js';
import wearableRoutes from './wearable.routes.js';
import superAdminRoutes from './superAdmin.routes.js';
import emergencyNetworkRoutes from './emergency-network.routes.js';
import healthRoutes from './health.routes.js';
import workerRoutes from './worker.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/ai', aiRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/reports', reportRoutes);
router.use('/assistant', assistantRoutes);
router.use('/medicine', medicineRoutes);
router.use('/system', systemRoutes);
router.use('/twin', twinRoutes);
router.use('/surveillance', surveillanceRoutes);
router.use('/admin', adminRoutes);
router.use('/interoperability', healthExchangeRoutes);
router.use('/hospitals', hospitalRoutes);
router.use('/doctors', doctorRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/labs', laboratoryRoutes);
router.use('/pharmacies', pharmacyRoutes);
router.use('/voice-assistant', voiceAssistantRoutes);
router.use('/mother-child', motherChildRoutes);
router.use('/government-schemes', governmentSchemesRoutes);
router.use('/emergency', emergencyRoutes);
router.use('/symptom-assessment', symptomAssessmentRoutes);
router.use('/family', familyRoutes);
router.use('/telemedicine', telemedicineRoutes);
router.use('/wearables', wearableRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/health', healthRoutes);
router.use('/emergency-network', emergencyNetworkRoutes);
router.use('/worker', workerRoutes);

export default router;
